// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkKQ5DreRaGV8AvJXC5c_pGWPH25g0o9k',
    appId: '1:1085945409884:web:dd0810584f1e6606b0d199',
    messagingSenderId: '1085945409884',
    projectId: 'pixeladventure-813e2',
    authDomain: 'pixeladventure-813e2.firebaseapp.com',
    storageBucket: 'pixeladventure-813e2.appspot.com',
    measurementId: 'G-0QSDY5YECR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO9DiFwoidh_kxiWUqtSBGKxoFz9QVjIU',
    appId: '1:1085945409884:android:3b475e8180e8ebfeb0d199',
    messagingSenderId: '1085945409884',
    projectId: 'pixeladventure-813e2',
    storageBucket: 'pixeladventure-813e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWVvQ8LlfgkZi7ni1EBn_kbsK4P6PV_j4',
    appId: '1:1085945409884:ios:225d47e0d6b74143b0d199',
    messagingSenderId: '1085945409884',
    projectId: 'pixeladventure-813e2',
    storageBucket: 'pixeladventure-813e2.appspot.com',
    iosBundleId: 'eurekamps.org.pixeladventure',
  );
}
